AkademikAraştirmaÖdev/Areas/area/Controllers/adminController.cs
using AkademikAraştirmaÖdev.Areas.area.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AkademikAraştirmaÖdev.Areas.area.Controllers
{
    public class adminController : Controller
    {
        AraştırmaEntities db = new AraştırmaEntities();
        [Authorize(Users = "artemiswolfs@gmail.com")]
        public ActionResult kitap()
        {
            var model = db.kitap.ToList();
            return View( model);
        }
        public ActionResult Add()
        {
          
            return View();
        }
        const string  imageFolderPath = "~/temaadm/resim/";
       
        /// <summary>
        /// 
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>

        public ActionResult KitapAdd(Class1 model)
        {
            string filename = string.Empty;
            if (model.resim != null && model.resim.ContentLength > 0)
            {
     
                filename = model.resim.FileName;
                var path = Path.Combine(Server.MapPath(imageFolderPath), filename);
                model.resim.SaveAs(path);

            }

            if (!ModelState.IsValid)
            {
                            
                kitap kitap = new kitap();
                kitap.kitapadı = model.kitapadı;
                kitap.kitapaçık = model.kitapaçık;
                kitap.kitaptarihi = DateTime.Now;
                kitap.kitaptürü = model.kitaptürü;
                kitap.kitaplink = imageFolderPath + filename;
                
                db.kitap.Add(kitap);
                db.SaveChanges();

            }
            return RedirectToAction("kitap");
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
             
            return View(db.kitap.Find(id));
        }
        [HttpPost]
        public ActionResult Edit(kitap model)
        {
            if (ModelState.IsValid)
            {

 
            db.Entry(model).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            }
            return RedirectToAction("kitap");
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            return View(db.kitap.Find(id));
        }
        [HttpGet]
        public ActionResult DeleteConfirm(int id)
        {
            db.kitap.Remove(db.kitap.Find(id));
            db.SaveChanges();
            return RedirectToAction("kitap");
        }
    }
   
    }

AkademikAraştirmaÖdev/Areas/area/Views/admin/Add.cshtml
@model AkademikAraştirmaÖdev.Areas.area.Models.Class1


@{
    ViewBag.Title = "Add";
    Layout = "~/Areas/area/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
    <div class="row">
        <div class="col-md-8">

            <div class="panel panel-default">
                <div class="panel-heading"><svg class="glyph stroked email"><use xlink:href="#stroked-email"></use></svg> Kitap Ekleme</div>
                <div class="panel-body"> 
                           @using (Html.BeginForm("KitapAdd", "admin", FormMethod.Post, new { @class = "form-horizontal", enctype = "multipart/form-data" }))
                           {
        
                                 <!-- Name input-->
                            <div class="form-group">
                                @Html.LabelFor(m => m.kitapadı, new { @class = "col-md-3 control-label" })
                          
                                <div class="col-md-9">
                                    @Html.TextBoxFor(m => m.kitapadı,new  {@class = "form-control", placeholder = "kitap adı" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.kitaptürü, new { @class = "col-md-3 control-label" })

                                <div class="col-md-9">
                                    @Html.TextBoxFor(m => m.kitaptürü, new { @class = "form-control", placeholder = "kitap türü" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.kitapaçık, new { @class = "col-md-3 control-label" })

                                <div class="col-md-9">
                                    @Html.TextBoxFor(m => m.kitapaçık, new { @class = "form-control", placeholder = "kitap açiklaması" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.resim, new { @class = "col-md-3 control-label" })

                                <div class="col-md-9">
                                    @Html.TextBoxFor(m => m.resim, new { @class = "form-control", placeholder = "kitap yolu" ,Type="file"})
                                </div>
                            </div>
                           
                  

                            <div class="form-group">
                                <div class="col-md-12 widget-right">
                                    <button type="submit" class="btn btn-default btn-md pull-right">Kayıt</button>
                                </div>
                            </div>
                           }                                          
                </div>
            </div>
        </div>
    </div>
  
</div>

AkademikAraştirmaÖdev/Areas/area/Views/admin/Delete.cshtml
@model AkademikAraştirmaÖdev.kitap

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/area/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
    <div class="row">
        <div class="col-md-8">

            <div class="panel panel-default">
                <div class="panel-heading"><svg class="glyph stroked email"><use xlink:href="#stroked-email"></use></svg> Kitap Silme</div>
                <div class="panel-body">

                    Silmek istediğinize emin misiniz?
                    <br />
                    @Model.kitapadı;
                    <br />
                    @Html.ActionLink("Kabul ediyorum", "DeleteConfirm", new { id = Model.id })
                    <br />
                    @Html.ActionLink("Kabul etmiyorum", "Kitap")
                    <br />
                </div>
            </div>
        </div>
    </div>
</div>

AkademikAraştirmaÖdev/Areas/area/Views/admin/Edit.cshtml
@model AkademikAraştirmaÖdev.kitap

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/area/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
        <div class="row">
            <div class="col-md-8">

                <div class="panel panel-default">
                    <div class="panel-heading"><svg class="glyph stroked email"><use xlink:href="#stroked-email"></use></svg> Kitap Ekleme</div>
                    <div class="panel-body">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.id)

                        <div class="form-group">
                            @Html.LabelFor(model => model.kitaptürü, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.kitaptürü, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.kitaptürü, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.kitapadı, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.kitapadı, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.kitapadı, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.kitapaçık, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.kitapaçık, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.kitapaçık, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.kitaplink, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.kitaplink, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.kitaplink, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Save" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

                    <div>
                        @Html.ActionLink("Back to List", "kitap")
                    </div>

AkademikAraştirmaÖdev/Areas/area/Views/admin/kitap.cshtml
@model List<kitap>
@{
    ViewBag.Title = "kitap";
    Layout = "~/Areas/area/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">Kitapları görüntüle</div>
                <div class="panel-body">
                    <table data-toggle="table" data-url="tables/data1.json" data-show-refresh="true" data-show-toggle="true" data-show-columns="true" data-search="true" data-select-item-name="toolbar1" data-pagination="true" data-sort-name="name" data-sort-order="desc">
                        <thead>
                            <tr>
                                <th>Kitap ID</th>
                                <th>Kitap Adı</th>
                                <th>Kitap Açıklaması</th>
                                <th>Kitap link</th>
                                <th>Kitap Tarihi</th>
                                <th>Kitap Türü</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.id</td>
                                    <td>@item.kitapadı  </td>
                                    <td>@item.kitapaçık  </td>
                                    <td>@item.kitaplink  </td>
                                    <td>@item.kitaptarihi   </td>
                                    <td>@item.kitaptürü   </td>
                                    <td>@Html.ActionLink("düzenle", "Edit", "admin",new {id=item.id }, null)| @Html.ActionLink("sil", "Delete", "admin", new { id = item.id }, null)  </td>
                                </tr>
                            }

                        </tbody>

                    </table>

                </div>
            </div>
        </div>
    </div>
   
</div>